version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
  backend:
    restart: always                 # restarting if mysql is not fully ready
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
  frontend:
    build: ./frontend/react-app
    ports:
      - "3000:3000"
